FIGHTERTEMPLATE_PROPERTIES = 
{
	grade     = { type="STRING" },
	traits    = { type="OBJECT" },

	--generated by grade and traits
	potential = { type="NUMBER" },
	hp        = { type="NUMBER" },
	st        = { type="NUMBER" },
	mp        = { type="NUMBER" },
	strength  = { type="NUMBER" },
	internal  = { type="NUMBER" },
	technique = { type="NUMBER" },
	agility   = { type="NUMBER" },

	skills    = { type="OBJECT" },
}


---------------------------------------
---------------------------------------
FIGHTERTEMPLATE_COMPONENT = class()


---------------------------------------